"""create vectorstore and filestorage models

Revision ID: 7dfd42990537
Revises: 
Create Date: 2023-02-19 23:19:03.664764

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7dfd42990537"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filestorage",
        sa.Column("fileId", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("fileId"),
    )
    op.create_table(
        "vectorstore",
        sa.Column("vectorstoreId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("vectorDb", sa.String(), nullable=False),
        sa.Column("urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("index_id", sa.UUID(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["index_id"], ["filestorage.fileId"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("vectorstoreId"),
    )
    op.create_table(
        "vectorstore_filestorage_association",
        sa.Column("vectorstoreId", sa.Integer(), nullable=False),
        sa.Column("fileId", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fileId"],
            ["filestorage.fileId"],
        ),
        sa.ForeignKeyConstraint(
            ["vectorstoreId"],
            ["vectorstore.vectorstoreId"],
        ),
        sa.PrimaryKeyConstraint("vectorstoreId", "fileId"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vectorstore_filestorage_association")
    op.drop_table("vectorstore")
    op.drop_table("filestorage")
    # ### end Alembic commands ###
