"""add embedding type to vectorstore

Revision ID: ab00d3aa4e78
Revises: 7dfd42990537
Create Date: 2023-03-02 00:18:54.529005

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab00d3aa4e78"
down_revision = "7dfd42990537"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vectorstore",
        sa.Column(
            "embeddingsType",
            sa.String(),
            nullable=False,
            server_default="huggingface_instruct",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vectorstore", "embeddingsType")
    # ### end Alembic commands ###
