name: solidchain
channels:
    - defaults
    - conda-forge
    # - pytorch
    # - huggingface
    # - xformers
    # - fastai
    - plotly
    # - pyviz
    # - rapidsai
    # - nvidia
dependencies:
    # Language
    - python>=3.10
    # - mamba
    # - conda-lock
    - pip
    # Common
    - numpy
    - pandas
    - scipy
    # - tqdm
    # - click
    # - geopandas>=0.11
    # - shapely

    # Visualization
    - matplotlib
    - seaborn
    # - ipympl
    # - altair
    # - yellowbrick
    - plotly::plotly
    # - holoviews
    # - bokeh
    # - datashader
    # - hiplot

    # Dashboards
    # - dash
    # - gradio
    # - streamlit
    # - voila
    # - panel

    # ML
    - scikit-learn
    # - imbalanced-learn
    # - xgboost
    # - catboost
    # - lightgbm
    # - statsmodels
    # - u8darts
    # - u8darts-all>=0.23.0
    # - sktime
    # - sktime-all-extras
    # - tslearn
    # - tsfresh>=0.19.0
    # - pytorch::pytorch>=1.10
    # - pytorch::torchvision
    # - pytorch::torchaudio
    # - pytorch::pytorch-cuda=11.7
    # - pytorch::cpuonly
    # - jax
    # - cuda-nvcc
    # - cudatoolkit=11.2
    # - cudnn=8.1.0
    # - keras
    # - fastai
    # - spacy
    # - transformers
    # - diffusers
    # - timm
    # - simulate
    # - accelerate
    # - optimum
    # - datasets
    # - tokenizers
    # - evaluate

    # Federated Learning
    # - syft
    # - flwr

    # XAI
    # - lime
    # - shap
    # - eli5
    # - alibi
    # - captum

    # Hyperparameters
    - optuna
    # - hyperopt

    # Experiment tracking
    # - wandb
    # - mlflow
    # - neptune-client
    # - hydra-core
    # - nevergrad
    # - ax-platform

    # Distributed
    # - modin-all
    # - dask
    # - ray
    # - ray-default
    # - rapids

    # Benchmarks
    # - snakeviz

    # Data format engines
    - pyarrow>=4.0
    # - pynio
    # - cfgrib # grib2 files
    # - netcdf4 # netCDF files
    # - openpyxl
    - python-multipart
    # - gdal<4.5 #They removed drivers requried by fiona for geopandas.
    # - fiona
    # - safetensors

    # Webservers
    # - flask
    - fastapi
    - uvicorn-standard
    # - gunicorn
    - pydantic

    # Databases / queues
    - psycopg2-binary
    # - psycopg2 # build whl file (aarch64 requirement - host needs libpq-dev)
    - sqlalchemy
    - alembic
    # - celery>=5.0
    - faiss-cpu

    # Scraping / http clients
    # - beautifulsoup4
    # - fake-useragent
    - httpx
    # - aiohttp

    # Utilities
    - pyyaml
    - arrow
    # - natsort
    # - cachetools
    # - astral
    # - pandas-ta

    - pip:
          # install in editable mode
          - -e ./apps/api

          # Pip only packages
          # - tensorflow
          # - tensorflow-probability
          # - flwr[simulation]
          - langchain
          - openai
          - unstructured[local-inference]
          - "detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2"

    ## Development
    # Environment
    - jupyterlab
    - ipython

    # Quality
    - black>=22
    # - ruff
    - isort
    - flake8
    # - mypy

    # SCM
    - pre_commit
    - nbdime
    - nbstripout

    # Teting
    # - pytest
    # - pytest-cov
    # - tox

    # Docs
    # - sphinx
    # - recommonmark
